### PR TITLE
ime: fix segfault when IME is killed

### LINKED ISSUE #2978: Segfault when killing IME
### Problem description

#2894 caused a regression that killing IME client like `fcitx5` causes segfault in labwc.

The cause is that `relay->input_method` is destroyed before `replay->input_method->keyboard_grab` is destroyed, so `replay->input_method` is `NULL` in keyboard grab's destroy handler.

https://github.com/labwc/labwc/blob/d87ef7568a97f03a84061feb94c7ce1dd37c11da/src/input/ime.c#L307-L308

I'll fix that soon.

### Steps to reproduce

1. Start `fcitx5`
2. Kill it
3. Labwc crashes

### labwc build source

Release

### labwc version

0.9.0-68-ge530f437-dirty (+xwayland +nls +rsvg +libsfdo)

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

_No response_

### PR DESCRIPTION
**Pull request by tokyo4j**
Fixes #2978 by partially reverting #2894.

Perhaps we can revert this PR again in wlroots 0.20 by reordering the emitted signals, I'm not sure (ref: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5107#note_3042631)

### CODE REVIEW

File: src/input/ime.c [hunk 1]
```diff
@@ -304,9 +304,7 @@ handle_keyboard_grab_destroy(struct wl_listener *listener, void *data)
 {
 	struct input_method_relay *relay =
 		wl_container_of(listener, relay, keyboard_grab_destroy);
-	struct wlr_input_method_keyboard_grab_v2 *keyboard_grab =
-		relay->input_method->keyboard_grab;
-
+	struct wlr_input_method_keyboard_grab_v2 *keyboard_grab = data;
```
Comment (Consolatis) [inline src/input/ime.c:307]: Suggest adding an `assert(data)` or `assert(keyboard_grab)` here to ensure that we remember to handle this when it is changed in future wlroots releases.

**Review by Consolatis — COMMENTED** [review]
Small future-proofing nitpick below. Other than that: LGTM

File: src/input/ime.c (hunk 1 above)
Comment (tokyo4j) [reply src/input/ime.c:307]: Thanks. Added `assert(keyboard_grab)`.
