### PR TITLE
session-lock: fix some bugs related to keyboard focus etc.

### LINKED ISSUE #1943: FollowMouse and swaylock: wrong window active
A very minor issue, but one that I find annoying.

I've got the following in my `rc.xml`:
```
  <focus>
    <followMouse>yes</followMouse>
    <followMouseRequiresMovement>no</followMouseRequiresMovement>
  </focus>
```
I also have the following in my `autostart` script:
```
swayidle -w \
	timeout 550 'swaylock -f -c 000000' \
	timeout 600 'wlopm --off \*' \
	resume 'wlopm --on \*' \
	before-sleep 'swaylock -f -c 000000' >/dev/null 2>&1 &
```
This works fairly well, in the sense that the active window is always the one under the mouse, except in one case: if swayidle triggers and swaylock locks the system, it is sometimes the case that the active window is not the one under the mouse.  Moving the mouse clears the discrepancy, but I occasionally end up typing in the wrong window, which is mildly annoying.

### PR DESCRIPTION
**Pull request by tokyo4j**
- Fix #1943
- Fix a bug I introduced in #1858 that allowed multiple clients to lock the screen.
- Clear keyboard focus on lock so keyboard events are never sent to normal surfaces once the screen is locked, even when the session-lock client haven't mapped its surface yet.

### CODE REVIEW

File: src/view.c [hunk 1]
```diff
@@ -2396,6 +2396,10 @@ view_destroy(struct view *view)
 		server->active_view = NULL;
 	}
 
+	if (server->session_lock_manager->last_active_view == view) {
+		server->last_raised_view = NULL;
+	}
```
Comment (Consolatis) [inline src/view.c:2401]: Looks like this resets the wrong view

File: src/session-lock.c [hunk 2]
```diff
@@ -266,25 +266,30 @@ handle_lock_unlock(struct wl_listener *listener, void *data)
 		wl_container_of(listener, manager, lock_unlock);
 	session_lock_destroy(manager);
 	manager->locked = false;
-	desktop_focus_topmost_view(manager->server);
+
+	if (manager->last_active_view) {
+		desktop_focus_view(manager->last_active_view, /* raise */ false);
+	}
```
Comment (Consolatis) [inline src/session-lock.c:272]: Should we have an else branch that focuses the topmost view here?

**Comment by Consolatis** [comment]
Other than the UX question above regarding focusing the topmost view if there isn't an last known active view this LGTM, not tested.

File: src/session-lock.c [hunk 3]
```diff
@@ -211,7 +211,10 @@ session_lock_output_create(struct session_lock_manager *manager, struct output *
 		goto exit_session;
 	}
 
-	/* Delay blanking output by 100ms to prevent flashing */
+	/*
+	 * Delay blanking output by 100ms to prevent flciker. If the session is
+	 * already locked, blank immediately.
```
Comment (Consolatis) [inline src/session-lock.c:216]: Nit: `s/flciker/flicker/`

Comment (tokyo4j) [reply src/session-lock.c:216]: Thanks.

File: src/session-lock.c (hunk 2 above)
Comment (tokyo4j) [reply src/session-lock.c]: Done.

I tried KDE Plasma (which doesn't use ext-session-lock) just now and I found it focuses on the last-focused window on unlock even when no window is focused on lock, so it will make a similar feeling.

**Comment by tokyo4j** [comment]
While testing this, I found killing `gtklock` reveals the normal views, which should be hidden by solid-color rectangles. I'll investigate and fix it.

**Comment by tokyo4j** [comment]
@Consolatis @johanmalm
Just to confirm, can I merge this PR?

All the functionalities are working in my test, including (un)plugging outputs while session is locked, killing `swaylock` and re-launching it, and launching multiple `swaylock` instances.

**Comment by johanmalm** [comment]
LGTM
Yes, please merge.
Grateful for the work on this.

**Comment by Consolatis** [comment]
> @Consolatis @johanmalm Just to confirm, can I merge this PR?

As a general statement, I completely trust your judgment in regards to code and testing PRs even if I didn't test them myself. Once you get a LGTM from at least one other project member feel free to go for the merge.

**Comment by tokyo4j** [comment]
> > @Consolatis @johanmalm Just to confirm, can I merge this PR?
> 
> As a general statement, I completely trust your judgment in regards to code and testing PRs even if I didn't test them myself. Once you get a LGTM from at least one other project member feel free to go for the merge.

Alright. I was a bit uncertain because small changes were made since your last LGTM, but yes, those changes don't require another LGTM as those were just adding `desktop_focus_topmost_view()` which you mentioned and non-functional refactors.

I'll have more confidence next time :)
