### PR TITLE
ssd: work around the translucent titlebar in pixman renderer

### LINKED ISSUE #2859: The center of the titlebar becomes translucent with `WLR_RENDERER=pixman`
### Problem description

When I launch labwc with `WLR_RENDERER=pixman`, the center of the titlebar becomes translucent even though I use the default theme.

Image

I guess this is a bug in wlroots renderer that a buffer becomes translucent if it is widened, and the bug became apparent with #2686. 

### Steps to reproduce

1. Set env var `WLR_RENDERER=pixman`
2. Launch labwc with the default configuration

### labwc build source

Local build

### labwc version

0.8.4-130-ge5a236ee-dirty

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

_No response_

### PR DESCRIPTION
**Pull request by tokyo4j**
Closes #2859.

This PR works around #2859 by using `WLR_SCALE_FILTER_NEAREST` filter mode if pixman renderer is used.

### CODE REVIEW

File: src/ssd/ssd-titlebar.c [hunk 1]
```diff
@@ -57,8 +58,18 @@ ssd_titlebar_create(struct ssd *ssd)
 		wl_list_init(&subtree->parts);
 
 		/* Background */
-		add_scene_buffer(&subtree->parts, LAB_SSD_PART_TITLEBAR, parent,
-			titlebar_fill, corner_width, 0);
+		struct wlr_scene_buffer *bg_scene_buffer =
+			wlr_scene_buffer_create(parent, titlebar_fill);
+		/* workaround: widened 1px buffer becomes translucent in pixman renderer */
```
Comment (Consolatis) [inline src/ssd/ssd-titlebar.c]: Could you add something like " TODO: remove once https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3990 is solved" to the comment?

**Comment by Consolatis** [comment]
Small nitpick above, other than that this LGTM to me. Not tested.

File: src/ssd/ssd-titlebar.c (hunk 1 above)
Comment (tokyo4j) [reply src/ssd/ssd-titlebar.c]: Added the suggested comment.
