### PR TITLE
action: fix UAF when using prompt during reconfigure

### LINKED ISSUE #3106: Use-after-free when labwc --reconfigure is run with prompt open
### Problem description

`action_prompt_create()` stores a raw pointer to a `struct action` in the `struct action_prompt` it creates. The `action_prompt` lives until the user closes the prompt, but the `action` can be freed earlier if `labwc --reconfigure` is run.

Thus, running `labwc --reconfigure` while a prompt is open causes use-after-free.

### Steps to reproduce

1. Add a keybind such as the example prompt to rc.xml:
```
    <keybind key="W-q">
      <action name="If">
        <prompt message="Quit?"/>
        <then>
          <action name="Exit"/>
        </then>
      </action>
    </keybind>
```

2. Start labwc nested.
3. Activate the keybind in the nested session. Do not click "Yes" or "No" yet.
4. Run `labwc --reconfigure` in the nested session.

```
=================================================================
==67914==ERROR: AddressSanitizer: heap-use-after-free on address 0x7bde7b5f79f0 at pc 0x56389b3570f1 bp 0x7ffe8e2f6380 sp 0x7ffe8e2f6370
READ of size 8 at 0x7bde7b5f79f0 thread T0
    #0 0x56389b3570f0 in action_get_arg ../src/action.c:277
    #1 0x56389b357666 in action_get_actionlist ../src/action.c:316
    #2 0x56389b35cd25 in action_check_prompt_result ../src/action.c:883
    #3 0x56389b3af166 in handle_sigchld ../src/server.c:162
    #4 0x7f9e8137085a  (/usr/lib/libwayland-server.so.0+0x585a) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #5 0x7f9e81375181 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xa181) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #6 0x7f9e81377296 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc296) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #7 0x56389b3863b0 in main ../src/main.c:268
    #8 0x7f9e7f227674  (/usr/lib/libc.so.6+0x27674) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #9 0x7f9e7f227728 in __libc_start_main (/usr/lib/libc.so.6+0x27728) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #10 0x56389b356304 in _start (/home/john/src/labwc/build/labwc+0x851304) (BuildId: 1f0a524fcf5ce295a5c003095be8eed81a592c5e)

0x7bde7b5f79f0 is located 32 bytes inside of 40-byte region [0x7bde7b5f79d0,0x7bde7b5f79f8)
freed by thread T0 here:
    #0 0x7f9e80d1f79d in free /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:51
    #1 0x56389b35a974 in action_free ../src/action.c:676
    #2 0x56389b35aace in action_list_free ../src/action.c:685
    #3 0x56389b4566dc in rcxml_finish ../src/config/rcxml.c:1929
    #4 0x56389b3ae682 in reload_config_and_theme ../src/server.c:82
    #5 0x56389b3aeb58 in handle_sighup ../src/server.c:112
    #6 0x7f9e8137085a  (/usr/lib/libwayland-server.so.0+0x585a) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #7 0x7f9e81375181 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xa181) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #8 0x7f9e81377296 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc296) (BuildId: b9664217748f523995e3f855fa197cf8e59942d1)
    #9 0x56389b3863b0 in main ../src/main.c:268
    #10 0x7f9e7f227674  (/usr/lib/libc.so.6+0x27674) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #11 0x7f9e7f227728 in __libc_start_main (/usr/lib/libc.so.6+0x27728) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #12 0x56389b356304 in _start (/home/john/src/labwc/build/labwc+0x851304) (BuildId: 1f0a524fcf5ce295a5c003095be8eed81a592c5e)

previously allocated by thread T0 here:
    #0 0x7f9e80d205dd in calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:74
    #1 0x56389b433868 in xzalloc ../src/common/mem.c:23
    #2 0x56389b359476 in action_create ../src/action.c:552
    #3 0x56389b4423c1 in parse_action ../src/config/rcxml.c:511
    #4 0x56389b44264f in append_parsed_actions ../src/config/rcxml.c:540
    #5 0x56389b442b54 in fill_keybind ../src/config/rcxml.c:567
    #6 0x56389b448a29 in entry ../src/config/rcxml.c:1046
    #7 0x56389b44d0a4 in traverse ../src/config/rcxml.c:1320
    #8 0x56389b44d0b7 in traverse ../src/config/rcxml.c:1321
    #9 0x56389b44d417 in rcxml_parse_xml ../src/config/rcxml.c:1339
    #10 0x56389b4557f6 in rcxml_read ../src/config/rcxml.c:1891
    #11 0x56389b385e63 in main ../src/main.c:220
    #12 0x7f9e7f227674  (/usr/lib/libc.so.6+0x27674) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #13 0x7f9e7f227728 in __libc_start_main (/usr/lib/libc.so.6+0x27728) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #14 0x56389b356304 in _start (/home/john/src/labwc/build/labwc+0x851304) (BuildId: 1f0a524fcf5ce295a5c003095be8eed81a592c5e)
```

### labwc build source

Release

### labwc version

master (26bd02d45730)

### labwc environment

Nested on Wayland

### Distribution

Arch Linux

### PR DESCRIPTION
**Pull request by johanmalm**
Reported-by: @jlindgren90

Fixes #3106

### CODE REVIEW

**Comment by johanmalm** [comment]
I could reproduce the crash. This patch fixes it for me.

File: src/server.c [hunk 1]
```diff
@@ -107,6 +107,9 @@ handle_sighup(int signal, void *data)
 {
 	struct server *server = data;
 
+	/* Avoid UAF when dialog client is used during reconfigure */
+	action_prompts_destroy();
```
Comment (Consolatis) [inline src/server.c]: Nitpick: seems to fit better into `reload_config_and_theme()`. Other than that LGTM.

Comment (johanmalm) [reply src/server.c]: Yes, I did ponder that. Okay, have moved it.
