### PR TITLE
keyboard: set keyboard layout on reconfigure

### LINKED ISSUE #1407: On-the-fly keyboard layout changes?
I can change the keyboard layout by setting XKB_DEFAULT_LAYOUT in ~/.config/labwc/environment and restarting labwc.

Is it possible to change the keyboard layout without having to restart labwc? Changing the value in environment and calling labwc --reconfigure doesn't work, and the environment file doesn't seem to be automatically monitored for changes. Updating the environment variable directly in a terminal doesn't work, either with or without a labwc --reconfigure.

I'm assuming this is possible - for some locales, people need to switch between two keymaps on the fly - but I can't see anything in the documentation other than just setting the environment variables.

### PR DESCRIPTION
**Pull request by johanmalm**
If keyboard-layout-per-toplevel-window is used, reset the group (index) for each window on --reconfigure whenever XKB_DEFAULT_LAYOUT has changed.

Refactor to use a common configure function for reconfigure and keyboard-group creation.

Co-authored-by: @johanmalm

Fixes #1407

### CODE REVIEW

**Comment by johanmalm** [comment]
I've given this some basic testing with single+multiple keyboard layouts. Seems to work, but could do with both code review + testing by others.

File: src/seat.c [hunk 1]
```diff
@@ -506,13 +506,51 @@ seat_finish(struct server *server)
...
+	if (!rc.kb_layout_per_window) {
+		return;
+	}
+
+	/*
+	 * We don't want to reset all window keyboard-layout groups on every
+	 * reconfigure unless XKB_DEFAULT_LAYOUT has actully changed.
+	 */
+	static char last_layout[64];
+	char *current_layout = getenv("XKB_DEFAULT_LAYOUT") ? : "";
```
Comment (ahesford) [inline src/seat.c:520]: Recommend avoiding the GNU extension to `?:`.

**Review by ahesford — COMMENTED** [review]
I'm not terribly familiar with input handling, but these changes seem reasonable.

File: src/seat.c [hunk 2]
```diff
@@ -506,13 +506,51 @@ seat_finish(struct server *server)
...
 {
+	if (!rc.kb_layout_per_window) {
+		return;
+	}
+
+	/*
+	 * We don't want to reset all window keyboard-layout groups on every
+	 * reconfigure unless XKB_DEFAULT_LAYOUT has actully changed.
+	 */
+	static char last_layout[64];
```
Comment (Consolatis) [inline src/seat.c:519]: I am not sure if 64 is enough. You can put of \*lot\* of options there.

File: src/input/keyboard.c [hunk 3]
```diff
@@ -592,11 +592,13 @@ keyboard_update_layout(struct seat *seat, xkb_layout_index_t layout)
...
 }
 
-void
-keyboard_init(struct seat *seat)
+/*
+ * Set layout based on environment variables XKB_DEFAULT_LAYOUT,
+ * XKB_DEFAULT_OPTIONS, and friends.
+ */
+static void
+set_layout(struct wlr_keyboard *kb)
```
Comment (Consolatis) [inline src/input/keyboard.c:600]: I think we should prevent setting the same keymap again. We can test for that with `wlr_keyboard_keymaps_match()`. 

That would also allow to call `reset_window_keyboard_layout_groups()` only when changing the keymap without us requiring to compare the single env var. The user might also have changed some system layout files or used other environment vars that influence the layout.

File: src/input/keyboard.c [hunk 4]
```diff
@@ -608,11 +610,30 @@ keyboard_init(struct seat *seat)
...
 	keybind_update_keycodes(seat->server);
 }
 
+void
+keyboard_group_init(struct seat *seat)
+{
+	if (seat->keyboard_group) {
+		wlr_log(WLR_ERROR, "keyboard group already exists - noop");
+		return;
+	}
```
Comment (Consolatis) [inline src/input/keyboard.c:631]: IMHO this should either be an `assert()` or we don't need to log here.

File: src/seat.c (hunk 1 above)
Comment (johanmalm) [reply src/seat.c]: Done

File: src/seat.c (hunk 2 above)
Comment (johanmalm) [reply src/seat.c]: Have increased to 1024.

File: src/input/keyboard.c (hunk 3 above)
Comment (johanmalm) [reply src/input/keyboard.c:600]: Nice catch. I didn't know about `wlr_keyboard_keymaps_match()`

File: src/input/keyboard.c (hunk 4 above)
Comment (johanmalm) [reply src/input/keyboard.c]: Done. `assert()` used.

File: src/input/keyboard.c (hunk 3 above)
Comment (johanmalm) [reply src/input/keyboard.c:600]: > That would also allow to call reset_window_keyboard_layout_groups() only when changing the keymap without us being required to compare the single env var. The user might also have changed some system layout files or used other environment vars that influence the keymap.

I'm not sure that works. For example, what if a user has changed group (e.g. `de` -> `se`) before a `--reconfigure`. That would then trigger a `reset_window_keyboard_layout_groups()` even though the `XKB_DEFAULT_LAYOUT` didn't change. Or is my brain just not thinking straight?

Comment (Consolatis) [reply src/input/keyboard.c:600]: > For example, what if a user has changed group (e.g. `de` -> `se`) before a `--reconfigure`.

Not sure I follow. You mean via `XKB_DEFAULT_LAYOUT`?

As long as the user doesn't change any system xkb files or one of the `XKB_` vars before a `--reconfigure` the keymap should be the same and thus we would not call `reset_window_keyboard_layout_groups()`.

Comment (johanmalm) [reply src/input/keyboard.c]: Yes, I'm stupid. I was thinking `group` rather than `keymap`. Have pushed fixup. Works fine now.

**Comment by johanmalm** [comment]
Okay. Have squashed. Ready for final review.

**Comment by Consolatis** [comment]
Code LGTM but I did not test at all.

**Comment by johanmalm** [comment]
Thanks for review... much better after your suggestions :smile:
Have tested again tonight. Seems to work fine.

**Comment by spl237** [comment]
Tested here - works fine for me. Many thanks!
