### PR TITLE
view: Use pending geometry for positioning logic

### LINKED ISSUE #671: Race condition while maximizing/unmaximizing windows
To reproduce:
Use this config file:
```
<?xml version="1.0"?>
<labwc_config>
  <keyboard>
    <default />
    <keybind key="A-Return">
      <action name="ToggleMaximize"></action>
    </keybind>

    <repeatRate>75</repeatRate>
    <repeatDelay>240</repeatDelay>
  </keyboard>
</labwc_config>
```

Open any window (at least, foot, various GTK programs, imv, and weston-terminal). Press and hold A-Enter, so the `ToggleMaximize` keybind repeats. Amidst maximizing and unmaximizing, the program will at some point forget its original unmaximized size, and begin toggling only between its original position and the top-left of the screen while always remaining the full size of the screen.

You may have to try pressing A-Enter several times--shorter, varied lengths tend to help. There also seems to be a repeat-rate dependence in this race condition--it's possible (but harder) to trigger it with a `repeatRate` of 60, and (so far in my tests) impossible to trigger with the default repeat rate. For what it's worth, my monitor runs at 60Hz, and I don't know if these repeat rates interact differently when the monitor runs at a different refresh rate.

While the window is maximizing/unmaximizing, various frames other than the expected two are also visible for fleeting moments, as well, such as titlebars that stick off the right edge of the screen (from a full-size but unmoved window).

### PR DESCRIPTION
**Pull request by jlindgren90**
- Make sure that `view->pending_move_resize` is always up-to-date for mapped views
- Use `view->pending_move_resize` rather than `view->x/y/w/h` for view positioning logic

By using the pending (most recently requested) dimensions instead of the current (displayed) dimensions of the view for positioning logic, we can avoid race conditions that might occur if we try to reposition a view while there is a pending move/resize that has not been processed yet.

This *should* fix #671 (I have not verified the fix since reproducing the issue looks quite involved).

It also greatly simplifies the logic that was committed in #680 since we can now use `view_center()` again, still without touching `view->w/h` before commit. I did test that there is no regression of that fix.

### CODE REVIEW

**Comment by jlindgren90** [comment]
Separately, I'd also suggest renaming:
- `view.x/y/w/h` to `view.geo.current`
- `view.pending_move_resize` to `view.geo.pending`
- `view.natural_geometry` to `view.geo.natural`

And use `struct wlr_box` for all three (I think this has been mentioned in passing before).
That would be a different pull request, though.

File: src/view.c [hunk 1]
```diff
@@ -417,7 +418,8 @@ view_apply_region_geometry(struct view *view)
 	geo.width -= margin.left + margin.right;
 	geo.height -= margin.top + margin.bottom;
 
-	if (view->w == geo.width && view->h == geo.height) {
+	if ((int)view->pending_move_resize.width == geo.width
```
Comment (Consolatis) [inline src/view.c:421]: Could we change `pending_move_resize.{width,height}` to int instead? It doesn't seem to make sense to have them as unsigned while everything else is signed. It also doesn't seem to be used all that much (on latest master, didn't check for this PR):
```
$ egrep -R 'pending_move_resize[.->]*(height|width)' src/
src/xwayland.c: view->pending_move_resize.width = geo.width;
src/xwayland.c: view->pending_move_resize.height = geo.height;
src/xwayland.c:         view->w = view->pending_move_resize.width;
src/xwayland.c:         view->h = view->pending_move_resize.height;
src/xdg.c:                              view->pending_move_resize.width - size.width;
src/xdg.c:                              view->pending_move_resize.height - size.height;
src/xdg.c:      view->pending_move_resize.width = geo.width;
src/xdg.c:      view->pending_move_resize.height = geo.height
```

File: src/view.c [hunk 2]
```diff
@@ -752,7 +755,12 @@ view_adjust_for_layout_change(struct view *view)
 		}
 	} else if (!view_apply_special_geometry(view)) {
 		/* reposition view if it's offscreen */
-		struct wlr_box box = { view->x, view->y, view->w, view->h };
+		struct wlr_box box = {
+			.x = view->pending_move_resize.x,
+			.y = view->pending_move_resize.y,
+			.width = view->pending_move_resize.width,
+			.height = view->pending_move_resize.height
+		};
```
Comment (Consolatis) [inline src/view.c:763]: This could just be a `struct wlr_box box = view->geo.pending` so another point for the refactor

File: src/view.c (hunk 1 above)
Comment (jlindgren90) [reply src/view.c:421]: `wlr_box.{width,height}` are `int` so we'd get that change for free if we go that route.

File: src/view.c (hunk 2 above)
Comment (jlindgren90) [reply src/view.c:763]: Yes indeed :)

If you prefer, I can submit that pull request (for the rename/refactor) and rebase this one on top.

File: src/view.c (hunk 1 above)
Comment (Consolatis) [reply src/view.c:421]: Right, I'd prefer to not have the casting everywhere but I don't really mind if we first do the `wlr_box` refactoring or switch the struct member to `int` in the meantime.

File: src/view.c (hunk 2 above)
Comment (Consolatis) [reply src/view.c:763]: Totally up to you :)

I'll put this PR into draft mode for now, but feel free to undraft it at any time.

**Comment by Consolatis** [comment]
The code change itself looks good to me but I didn't test.

**Comment by jlindgren90** [comment]
Rebased. Diff is a lot cleaner now after the `wlr_box` refactor.

**Comment by Consolatis** [comment]
> Diff is a lot cleaner now after the `wlr_box` refactor.

Indeed, very much so. Thanks

**Comment by Consolatis** [comment]
Btw, in my opinion the separation of view.c `apply_xxx_geometry()` and the actions which merely compute the sizes + deal with the global state and now the clear separation of `current` `pending` and `natural` geometry are two of the most important changes for the labwc codebase from a design and maintainability perspective. Had to be said somewhere so why not here.
